ALTER TABLE HUBMAIL_Messages ALTER COLUMN ToText NVARCHAR(MAX) NULL;
ALTER TABLE HUBMAIL_Messages ALTER COLUMN CcText NVARCHAR(MAX) NULL;
ALTER TABLE HUBMAIL_Messages ALTER COLUMN Subject NVARCHAR(2000) NULL;
ALTER TABLE HUBMAIL_Messages ALTER COLUMN MessageIdHeader NVARCHAR(2000) NULL;
ALTER TABLE HUBMAIL_Messages ALTER COLUMN InReplyTo NVARCHAR(2000) NULL;
ALTER TABLE HUBMAIL_Messages ALTER COLUMN FromName NVARCHAR(2000) NULL;
ALTER TABLE HUBMAIL_Messages ALTER COLUMN FromEmail NVARCHAR(2000) NULL;