CREATE TABLE IF NOT EXISTS HUBMAIL_Accounts (
    AccountID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    EmailAddress VARCHAR(255) NOT NULL,
    DisplayName VARCHAR(200) NULL,
    IMAPHost VARCHAR(255) NOT NULL,
    IMAPPort INT NOT NULL,
    SMTPHost VARCHAR(255) NOT NULL,
    SMTPPort INT NOT NULL,
    Username VARCHAR(255) NOT NULL,
    PasswordEnc TEXT NOT NULL,
    SignatureHtml LONGTEXT NULL,
    IsDefault TINYINT(1) NOT NULL DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CanonicalAccountID INT NULL,
    Phone VARCHAR(50) NULL,
    Color VARCHAR(20) NULL,
    UNIQUE KEY UQ_HUBMAIL_Accounts (UserID, EmailAddress),
    KEY IX_HUBMAIL_Accounts_User (UserID)
);

CREATE TABLE IF NOT EXISTS HUBMAIL_Contacts (
    ContactID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(50) NULL,
    Notes VARCHAR(500) NULL,
    CreatedBy INT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_HUBMAIL_Contacts_Email (Email)
);

CREATE TABLE IF NOT EXISTS HUBMAIL_Unread (
    AccountID INT NOT NULL PRIMARY KEY,
    LastCheck DATETIME NULL,
    UnreadCount INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS HUBMAIL_SyncState (
    AccountID INT NOT NULL,
    Folder VARCHAR(500) NOT NULL,
    LastSync DATETIME NULL,
    TotalCount INT NOT NULL DEFAULT 0,
    PRIMARY KEY (AccountID, Folder)
);

CREATE TABLE IF NOT EXISTS HUBMAIL_Messages (
    MsgID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AccountID INT NOT NULL,
    Folder VARCHAR(500) NOT NULL,
    UID BIGINT NOT NULL,
    MessageIdHeader VARCHAR(2000) NULL,
    InReplyTo VARCHAR(2000) NULL,
    FromName VARCHAR(2000) NULL,
    FromEmail VARCHAR(2000) NULL,
    ToText LONGTEXT NULL,
    CcText LONGTEXT NULL,
    Subject VARCHAR(2000) NULL,
    DateSent DATETIME NULL,
    Seen TINYINT(1) NOT NULL DEFAULT 0,
    Answered TINYINT(1) NOT NULL DEFAULT 0,
    Flagged TINYINT(1) NOT NULL DEFAULT 0,
    Deleted TINYINT(1) NOT NULL DEFAULT 0,
    Draft TINYINT(1) NOT NULL DEFAULT 0,
    HasAttachments TINYINT(1) NOT NULL DEFAULT 0,
    BodyHtml LONGTEXT NULL,
    BodyText LONGTEXT NULL,
    Size INT NOT NULL DEFAULT 0,
    SyncedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Spam TINYINT(1) NOT NULL DEFAULT 0,
    SenderIP VARCHAR(64) NULL,
    UNIQUE KEY UQ_HUBMAIL_Messages_UID (AccountID, Folder, UID),
    KEY IX_HUBMAIL_Messages_List (AccountID, Folder, DateSent),
    KEY IX_HUBMAIL_Messages_Unread (AccountID, Folder, Seen)
);

CREATE TABLE IF NOT EXISTS HUBMAIL_UserSettings (
    UserID INT NOT NULL PRIMARY KEY,
    DisplayName VARCHAR(120) NULL,
    Phone VARCHAR(50) NULL,
    SignatureHtml LONGTEXT NULL
);

CREATE TABLE IF NOT EXISTS HUBMAIL_Admins (
    UserID INT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS HUBMAIL_SpamLists (
    ListId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Type VARCHAR(10) NOT NULL DEFAULT 'DNSBL',
    Zone VARCHAR(150) NOT NULL,
    Enabled TINYINT(1) NOT NULL DEFAULT 1,
    Priority INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS HUBMAIL_Filters (
    FilterID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Scope VARCHAR(10) NOT NULL DEFAULT 'ACCOUNT',
    AccountID INT NULL,
    Name VARCHAR(100) NOT NULL,
    Conditions LONGTEXT NOT NULL,
    Action VARCHAR(20) NOT NULL,
    ActionFolder VARCHAR(255) NULL,
    Enabled TINYINT(1) NOT NULL DEFAULT 1,
    OrderNo INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS HUBMAIL_AddressBook (
    EntryID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NULL,
    LastContact DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_HUBMAIL_AddrBook (UserID, Email),
    KEY IX_HUBMAIL_AddrBook_User (UserID)
);

CREATE TABLE IF NOT EXISTS HUBMAIL_UserMeta (
    UserID INT NOT NULL PRIMARY KEY,
    LastLogin DATETIME NULL
);

CREATE TABLE IF NOT EXISTS HUBMAIL_Attachments (
    AttachID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AccountID INT NOT NULL,
    Folder VARCHAR(500) NOT NULL,
    UID BIGINT NOT NULL,
    Name VARCHAR(500) NULL,
    ContentType VARCHAR(200) NULL,
    Cid VARCHAR(500) NULL,
    Size INT NOT NULL DEFAULT 0,
    Data LONGBLOB NULL,
    SyncedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY IX_HUBMAIL_Attachments_Msg (AccountID, Folder, UID)
);

CREATE TABLE IF NOT EXISTS HUBMAIL_Folders (
    AccountID INT NOT NULL,
    Folder VARCHAR(500) NOT NULL,
    Delimiter VARCHAR(10) NULL,
    Flags VARCHAR(500) NULL,
    SyncedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (AccountID, Folder)
);

CREATE TABLE IF NOT EXISTS HUBMAIL_Retention (
    AccountID INT NOT NULL PRIMARY KEY,
    LastRun DATETIME NULL
);

CREATE TABLE IF NOT EXISTS HUBMAIL_ActivityLog (
    LogID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AccountID INT NULL,
    UserID INT NOT NULL,
    UserName VARCHAR(200) NULL,
    Action VARCHAR(100) NOT NULL,
    Details VARCHAR(1000) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY IX_HUBMAIL_ActivityLog_Acc (AccountID, CreatedAt),
    KEY IX_HUBMAIL_ActivityLog_User (UserID, CreatedAt)
);