CREATE TABLE IF NOT EXISTS HUBMAIL_PendingOps (
    OpID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AccountID INT NOT NULL,
    OpType VARCHAR(20) NOT NULL,
    Folder VARCHAR(500) NOT NULL,
    UID BIGINT NOT NULL,
    Value TINYINT NULL,
    DestFolder VARCHAR(500) NULL,
    DestAccountID INT NULL,
    MsgId VARCHAR(2000) NULL,
    Status VARCHAR(10) NOT NULL DEFAULT 'pending',
    Error VARCHAR(1000) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_pending (AccountID, Status)
);