CREATE TABLE IF NOT EXISTS HUBMAIL_PushSubscriptions (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Endpoint VARCHAR(1000) NOT NULL,
    P256DH VARCHAR(255) NOT NULL,
    Auth VARCHAR(255) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_push_endpoint (Endpoint(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;