CREATE TABLE IF NOT EXISTS HUBMAIL_SyncErrors (
    ErrorID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AccountID INT NOT NULL,
    Folder VARCHAR(500) NULL,
    Error VARCHAR(2000) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY IX_HUBMAIL_SyncErrors_Acc (AccountID, CreatedAt),
    KEY IX_HUBMAIL_SyncErrors_Time (CreatedAt)
);